[package]
name = "ltx_lexer"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ltx_diagnostics = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
criterion = { workspace = true }
[lints]
workspace = true

[[bench]]
name = "catcode_bench"
harness = false

[[bench]]
name = "lexer_bench"
harness = false
