[package]
name = "ltx_parser"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ltx_diagnostics = { workspace = true }
ltx_lexer = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
criterion = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "parser_bench"
harness = false
